version: '3'

services:
  db_tattoo:
    build: ./services/db
    container_name: tattoo_db
    restart: "no"
    env_file: .env
    volumes:
      - psql_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - 5432:5432  # for debugging
    networks:
      - backend

  nginx_tattoo:
    build: ./services/nginx
    container_name: tattoo_nginx
    restart: "no"
    ports:
      - 80:80
      - 8090:8090
    volumes:
      - ./static:/var/www/src/static
      - ./media:/var/www/src/media
    links:
      - app_tattoo
    depends_on:
      - app_tattoo
    networks:
      - frontend
      - backend

  app_tattoo:
    build:
      context: ./
      dockerfile: services/app/Dockerfile
      args:
        - BUILD_ENV=dev
        - REQUIREMENTS=base
    image: tattoo_app:latest
    container_name: tattoo
    command: ${SYSTEM_UP_COMMAND}
    restart: "no"
    env_file: .env
    volumes:
      - .:/var/www/src
      # mount all code except a few folders:
      - ./static:/var/www/src/static
      - ./media:/var/www/src/media
      - ./services/app/docker-entrypoint.sh:/docker-entrypoint.sh
    depends_on:
      - db_tattoo
    links:
      - db_tattoo
    ports:
      - 8000:8000
      - 3000:3000
    networks:
      - frontend
      - backend

volumes:
  psql_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge